### ISSUE TITLE
React Router

### ISSUE THREAD

**Issue by kalecodes** [kalecodes/dev-portfolio#1]
* Implement React Router functionality to provide a multi-page feel

**Comment by VitorCorrea98** [comment]
if you want to just lead to the resume page on the same page try putting on your css html{
    scroll-behavior: smooth;
}

and on the a tag on your html code you need to use a href="#idOfSectionYouNeed" and have that id on your html section

for example:

<section id="resume"> This is my resume section </section>

<a href="#resume">Resume</a>


this should work and scroll smoth with your html set to scroll-behavior: smooth
