### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by kalecodes** [kalecodes/dev-portfolio#2]
* Convert copy of resume to an image format and embed on page. 
* Include a link to download resume

**Comment by brahmbeyond** [comment]
sir, i want to work on this part.
But can you please elaborate what exactly you want  as 'view my resume' button doesn't lead anywhere  and also I'm not an experienced one,

**Comment by kalecodes** [comment]
@autumn-absconds Hey! This repo is a personal project, I am not looking for outside contributions at this time, I appreciate the offer!
